# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SNCurve.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SN_Curve(object):
    def setupUi(self, SN_Curve):
        SN_Curve.setObjectName("SN_Curve")
        SN_Curve.resize(522, 559)
        SN_Curve.setFixedSize(522, 559)
        self.widget = QtWidgets.QWidget(SN_Curve)
        self.widget.setObjectName("widget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 311, 451))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setTabletTracking(False)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.RpMPa = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.RpMPa.setFont(font)
        self.RpMPa.setObjectName("RpMPa")
        self.verticalLayout.addWidget(self.RpMPa)
        self.thickness = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.thickness.setFont(font)
        self.thickness.setObjectName("thickness")
        self.verticalLayout.addWidget(self.thickness)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.widget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(350, 20, 151, 452))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.l_mat = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.l_mat.setFont(font)
        self.l_mat.setObjectName("l_mat")
        self.l_mat.addItem("")
        self.l_mat.addItem("")
        self.verticalLayout_2.addWidget(self.l_mat)
        self.l_Rm = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.l_Rm.setFont(font)
        self.l_Rm.setObjectName("l_Rm")
        self.verticalLayout_2.addWidget(self.l_Rm)
        self.l_Rp = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.l_Rp.setFont(font)
        self.l_Rp.setObjectName("l_Rp")
        self.verticalLayout_2.addWidget(self.l_Rp)
        self.l_t = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.l_t.setFont(font)
        self.l_t.setObjectName("l_t")
        self.verticalLayout_2.addWidget(self.l_t)
        self.l_Rz = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.l_Rz.setFont(font)
        self.l_Rz.setObjectName("l_Rz")
        self.verticalLayout_2.addWidget(self.l_Rz)
        self.l_j = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.l_j.setFont(font)
        self.l_j.setObjectName("l_j")
        self.verticalLayout_2.addWidget(self.l_j)
        self.l_j_0 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.l_j_0.setFont(font)
        self.l_j_0.setObjectName("l_j_0")
        self.verticalLayout_2.addWidget(self.l_j_0)
        self.l_S_pu = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.l_S_pu.setFont(font)
        self.l_S_pu.setObjectName("l_S_pu")
        self.verticalLayout_2.addWidget(self.l_S_pu)
        self.l_gamma_M = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.l_gamma_M.setFont(font)
        self.l_gamma_M.setObjectName("l_gamma_M")
        self.verticalLayout_2.addWidget(self.l_gamma_M)
        self.check_t_c = QtWidgets.QCheckBox(self.widget)
        self.check_t_c.setGeometry(QtCore.QRect(20, 490, 291, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.check_t_c.setFont(font)
        self.check_t_c.setObjectName("check_t_c")
        self.Cal_Plot = QtWidgets.QPushButton(self.widget)
        self.Cal_Plot.setGeometry(QtCore.QRect(300, 490, 201, 37))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Cal_Plot.setFont(font)
        self.Cal_Plot.setObjectName("Cal_Plot")
        SN_Curve.setCentralWidget(self.widget)

        self.retranslateUi(SN_Curve)
        QtCore.QMetaObject.connectSlotsByName(SN_Curve)

    def retranslateUi(self, SN_Curve):
        _translate = QtCore.QCoreApplication.translate
        SN_Curve.setWindowTitle(_translate("SN_Curve", "SN Curve Calculation"))
        self.label.setText(_translate("SN_Curve", "<html><head/><body><p align=\"right\">Material</p></body></html>"))
        self.label_2.setText(_translate("SN_Curve", "<html><head/><body><p align=\"right\">Rm/MPa</p></body></html>"))
        self.RpMPa.setText(_translate("SN_Curve", "<html><head/><body><p align=\"right\">Rp/MPa</p></body></html>"))
        self.thickness.setText(_translate("SN_Curve", "<html><head/><body><p align=\"right\">Thickness/mm</p></body></html>"))
        self.label_5.setText(_translate("SN_Curve", "<html><head/><body><p align=\"right\">Surface roughness/mm</p></body></html>"))
        self.label_6.setText(_translate("SN_Curve", "<html><head/><body><p align=\"right\">Component quality / j</p></body></html>"))
        self.label_7.setText(_translate("SN_Curve", "<html><head/><body><p align=\"right\">Material constant / j0</p></body></html>"))
        self.label_8.setText(_translate("SN_Curve", "<html><head/><body><p align=\"right\">Survival probability</p></body></html>"))
        self.label_9.setText(_translate("SN_Curve", "<html><head/><body><p align=\"right\">Partial factor / γ<span style=\" vertical-align:sub;\">m</span></p></body></html>"))
        self.l_mat.setItemText(0, _translate("SN_Curve", "GGG"))
        self.l_mat.setItemText(1, _translate("SN_Curve", "Others"))
        self.l_Rm.setText(_translate("SN_Curve", "360"))
        self.l_Rp.setText(_translate("SN_Curve", "220"))
        self.l_t.setText(_translate("SN_Curve", "60"))
        self.l_Rz.setText(_translate("SN_Curve", "125"))
        self.l_j.setText(_translate("SN_Curve", "3"))
        self.l_j_0.setText(_translate("SN_Curve", "1"))
        self.l_S_pu.setText(_translate("SN_Curve", "0.667"))
        self.l_gamma_M.setText(_translate("SN_Curve", "1.265"))
        self.check_t_c.setToolTip(_translate("SN_Curve", "<html><head/><body><p align=\"right\"><br/></p></body></html>"))
        self.check_t_c.setText(_translate("SN_Curve", "Thickness correction"))
        self.Cal_Plot.setText(_translate("SN_Curve", "Cal and plot"))
